name:                lisby1
version:             0.1.0.0
github:              "githubuser/lisby1"
license:             BSD3
author:              "Marcus Ofenhed"
maintainer:          "marcus.ofenhed@nixu.com"
copyright:           "2019 Marcus Ofenhed"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lisby1#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- binary
- mtl
- containers
- vector

library:
  source-dirs: src

executables:
  lisby1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - lisby1
